version: '3'
services:
    postgres:
        restart: always
        image: postgres
        environment:
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_USER: 'postgres'
        volumes:
           - ./postgres:/var/lib/postgresql/data
        ports:
          - 5555:5432
    datapull:
        build: ./scrape
        depends_on:
            - postgres
        volumes:
            - ./scrape:/app